import { useEffect, useMemo, useState } from 'react'

const SAVED_KEY = 'commanderDeckAnalyzer.savedDecks.v2'
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

const ROLE_COLORS = {
  Ramp: '#f59e0b', Draw: '#06b6d4', Removal: '#ef4444', 'Board Wipe': '#dc2626', Counterspell: '#38bdf8', Protection: '#22c55e', Tutor: '#e879f9', Tokens: '#84cc16', 'Sac Outlet': '#f97316', Untap: '#a3e635', Evasion: '#facc15', Drain: '#a855f7', Lifegain: '#ec4899', Recursion: '#3b82f6', Reanimator: '#2563eb', Voltron: '#facc15', Equipment: '#eab308', Blink: '#93c5fd', ETB: '#60a5fa', Spellslinger: '#818cf8', Artifacts: '#fbbf24', Enchantress: '#f472b6', Tribal: '#4ade80', Counters: '#34d399', Proliferate: '#2dd4bf', Stax: '#f43f5e', Goad: '#fb7185', Theft: '#fb923c', 'Extra Turns': '#c084fc', 'Mass Land Denial': '#f97316', 'Game Changer': '#facc15', 'Fast Mana': '#fde047', Combo: '#c084fc', Finisher: '#dc2626', Land: '#6b7280', Other: '#6b7280'
}

const ROLE_DESCRIPTIONS = {
  Ramp: 'Acelera maná: rocks, dorks, land ramp, tesoros o jugar más tierras.',
  Draw: 'Robo de cartas o ventaja de cartas: draw, investigate, clues o cartas a mano.',
  Removal: 'Respuesta puntual: destruir, exiliar, bounce, fight o daño a objetivo.',
  'Board Wipe': 'Limpieza global: destruye/exilia muchas criaturas o permanentes, daño global o -X/-X.',
  Counterspell: 'Contrahechizos o respuestas a habilidades en la pila.',
  Protection: 'Protege piezas clave: hexproof, indestructible, phase out, ward, boots, etc.',
  Tutor: 'Busca cartas en la biblioteca que no son solo tierras.',
  Tokens: 'Crea fichas o usa fichas como parte importante del plan.',
  'Sac Outlet': 'Permite sacrificar criaturas/permanentes como coste o motor.',
  Untap: 'Endereza permanentes o habilita loops con cartas que se giran.',
  Evasion: 'Ayuda a conectar daño: flying, trample, menace, unblockable, etc.',
  Drain: 'Hace perder vida a oponentes, normalmente ligado a aristocrats/lifegain.',
  Lifegain: 'Gana vida o convierte eventos en ganancia de vida.',
  Recursion: 'Recupera cartas del cementerio a mano/biblioteca o permite reutilizarlas.',
  Reanimator: 'Devuelve criaturas directamente del cementerio al campo de batalla.',
  Voltron: 'Mejora una criatura/comandante para ganar por daño directo/comandante.',
  Equipment: 'Equipo o sinergia explícita con equipos.',
  Blink: 'Exilia y devuelve permanentes para repetir ETB/proteger.',
  ETB: 'Tiene o premia entradas al campo de batalla.',
  Spellslinger: 'Premia lanzar/copiar instantáneos y conjuros.',
  Artifacts: 'Sinergia real con artefactos, no simplemente ser un artefacto.',
  Enchantress: 'Sinergia con encantamientos, auras o constellation.',
  Tribal: 'Se apoya en tipos de criatura, lords o kindred.',
  Counters: 'Pone, mueve, duplica o se beneficia de contadores.',
  Proliferate: 'Prolifera contadores en permanentes/jugadores.',
  Stax: 'Limita acciones de jugadores: impuestos, no lanzar, no enderezar, etc.',
  Goad: 'Fuerza criaturas rivales a atacar a otros si pueden.',
  Theft: 'Roba/controla cartas o juega cartas de oponentes.',
  'Extra Turns': 'Da turnos extra.',
  'Mass Land Denial': 'Destruye/niega tierras o bloquea recursos masivos.',
  'Game Changer': 'Carta de alto impacto para estimar bracket.',
  'Fast Mana': 'Aceleración explosiva por encima del ramp normal.',
  Combo: 'Pieza que permite ganar o generar bucles decisivos.',
  Finisher: 'Carta que ayuda a cerrar la partida.'
}

const GAME_CHANGERS = new Set(['drannith magistrate','enlightened tutor','serra\'s sanctum','smothering tithe','trouble in pairs','cyclonic rift','expropriate','force of will','fierce guardianship','rhystic study','thassa\'s oracle','urza, lord high artificer','mystical tutor','bolas\'s citadel','demonic tutor','imperial seal','opposition agent','tergrid, god of fright','vampiric tutor','ad nauseam','jeska\'s will','gaea\'s cradle','underworld breach','survival of the fittest','vorinclex, voice of hunger','the one ring','trinisphere','chrome mox','grim monolith','lion\'s eye diamond','mox diamond','mana vault','ancient tomb','kinnan, bonder prodigy','yuriko, the tiger\'s shadow','winota, joiner of forces','grand arbiter augustin iv'])
const FAST_MANA = new Set(['mana crypt','mana vault','chrome mox','mox diamond','mox opal','lion\'s eye diamond','grim monolith','ancient tomb','jeweled lotus'])
const STRONG_TUTORS = new Set(['demonic tutor','vampiric tutor','imperial seal','mystical tutor','enlightened tutor','worldly tutor','personal tutor','gamble','entomb','intuition'])
const MLD = new Set(['armageddon','ravages of war','jokulhaups','obliterate','decree of annihilation','ruination','winter orb','static orb','stasis','worldslayer'])
const EXTRA_TURNS = new Set(['time warp','temporal manipulation','capture of jingzhou','nexus of fate','expropriate','time stretch','alrund\'s epiphany','walk the aeons'])

const COMBOS = [
  combo('Exquisite Blood + Sanguine Bond', ['Exquisite Blood','Sanguine Bond'], 'Infinite lifedrain', ['Infinite lifegain','Infinite lifedrain','Win line'], 'Alta', 'Cuando un oponente pierde vida, ganás vida; Sanguine Bond vuelve a hacerle perder vida y se repite.', ['Controlá ambas piezas.','Hacé que un oponente pierda vida o ganá vida.','El trigger de una pieza dispara la otra y el loop se repite.'], ['Necesitás iniciar el loop con una pérdida/ganancia de vida.']),
  combo('Exquisite Blood + Dina, Soul Steeper', ['Exquisite Blood','Dina, Soul Steeper'], 'Infinite lifedrain', ['Infinite lifegain','Infinite lifedrain','Win line'], 'Alta', 'Dina hace perder vida al ganar vida; Exquisite Blood vuelve a ganar vida y el loop se repite.', ['Controlá Dina y Exquisite Blood.','Ganá vida por cualquier fuente.','Dina drena y Exquisite Blood vuelve a darte vida.'], ['Necesitás iniciar el loop ganando vida.']),
  combo('Ashaya, Soul of the Wild + Quirion Ranger', ['Ashaya, Soul of the Wild','Quirion Ranger'], 'Infinite untap / ETB loop', ['Infinite ETB','Infinite landfall triggers','Infinite LTB','Infinite storm count'], 'Alta', 'Ashaya convierte criaturas no-token en Bosques; Quirion Ranger puede devolverse a sí misma para enderezar otra criatura.', ['Controlá Ashaya y Quirion Ranger.','Activá Quirion Ranger devolviéndose a sí misma para enderezar una criatura.','Volvé a lanzar Quirion Ranger y repetí.'], ['Controlás una criatura no-token útil para enderezar.']),
  combo('Selvala, Heart of the Wilds + Umbral Mantle', ['Selvala, Heart of the Wilds','Umbral Mantle'], 'Infinite mana / power', ['Infinite green mana','Infinite creature power','Infinite untap'], 'Alta', 'Si Selvala genera al menos 4 manás, Umbral Mantle permite enderezarla y darle +2/+2, aumentando el maná que produce.', ['Equipá Umbral Mantle a Selvala.','Activá Selvala para agregar maná.','Pagá 3 para enderezarla y darle +2/+2.','Repetí.'], ['Selvala debe poder girarse y generar 4+ manás.']),
  combo('Ivy Lane Denizen + Herd Baloth', ['Ivy Lane Denizen','Herd Baloth'], 'Infinite tokens / counters', ['Infinite tokens','Infinite +1/+1 counters','Infinite ETB'], 'Media-Alta', 'Cada contador +1/+1 en Herd Baloth crea una Bestia verde, que dispara Ivy Lane Denizen para poner otro contador.', ['Controlá ambas piezas.','Poné un contador sobre Herd Baloth.','Crea una ficha, dispara Ivy Lane, pone otro contador.'], ['Necesitás iniciar poniendo un contador.']),
  combo('Thassa\'s Oracle + Demonic Consultation', ['Thassa\'s Oracle','Demonic Consultation'], 'Win the game', ['Win the game','Library exile'], 'cEDH', 'Exilia la biblioteca y gana con el trigger de Oracle.', ['Lanzá Oracle.','Con el trigger en pila, lanzá Consultation.','Resolvé Oracle y ganá.'], ['Necesitás resolver ambas cartas.']),
  combo('Thassa\'s Oracle + Tainted Pact', ['Thassa\'s Oracle','Tainted Pact'], 'Win the game', ['Win the game','Library exile'], 'cEDH', 'Otra línea compacta de Oracle para ganar inmediatamente.', ['Lanzá Oracle.','Con el trigger en pila, resolvé Tainted Pact.','Resolvé Oracle.'], ['La lista debe soportar Tainted Pact.']),
  combo('Kiki-Jiki + Zealous Conscripts', ['Kiki-Jiki, Mirror Breaker','Zealous Conscripts'], 'Infinite tokens', ['Infinite hasty tokens','Combat win'], 'Alta', 'Crea copias infinitas con prisa para ganar por combate.', ['Copiá Zealous Conscripts.','La copia endereza Kiki-Jiki.','Repetí.'], ['Kiki-Jiki debe poder girarse.']),
  combo('Isochron Scepter + Dramatic Reversal', ['Isochron Scepter','Dramatic Reversal'], 'Infinite mana', ['Infinite mana','Infinite untap'], 'Alta', 'Con rocas que produzcan 3+ manás, genera maná infinito.', ['Imprimí Dramatic Reversal.','Generá 3+ manás con rocas.','Activá Scepter y repetí.'], ['Permanentes no-tierra producen más que el coste.']),
  combo('Underworld Breach + LED + Brain Freeze', ['Underworld Breach','Lion\'s Eye Diamond','Brain Freeze'], 'Storm / Win', ['Storm loop','Self-mill','Win line'], 'cEDH', 'Loop de cementerio y storm para deckear o ganar con Breach.', ['Controlá Breach.','Usá LED y Brain Freeze repetidamente.','Acumulá storm/mill.'], ['Suficientes cartas en cementerio.']),
  combo('Heliod + Walking Ballista', ['Heliod, Sun-Crowned','Walking Ballista'], 'Infinite damage/lifegain', ['Infinite damage','Infinite lifegain'], 'Alta', 'Ballista con lifelink dispara Heliod y vuelve a poner contadores.', ['Dale lifelink a Ballista.','Quitá contador para hacer daño.','Ganás vida y Heliod repone el contador.'], ['Ballista necesita suficientes contadores.']),
  combo('Mikaeus + Triskelion', ['Mikaeus, the Unhallowed','Triskelion'], 'Infinite damage', ['Infinite damage','Death loop'], 'Alta', 'Triskelion muere y vuelve con undying para repetir daño.', ['Controlá ambas.','Usá contadores de Triskelion para dañar.','Muere, vuelve, repetí.'], ['Triskelion debe poder morir.']),
  combo('Scurry Oak + Rosie Cotton', ['Scurry Oak','Rosie Cotton of South Lane'], 'Infinite tokens/counters', ['Infinite tokens','Infinite counters','Infinite ETB'], 'Media-Alta', 'Cada token pone contador, que crea otro token y repite.', ['Poné contador en Scurry Oak.','Crea token.','Rosie pone otro contador.'], ['Necesitás iniciar con un contador.']),
  combo('Avacyn + Worldslayer', ['Avacyn, Angel of Hope','Worldslayer'], 'Mass land denial / Lock', ['Destroy all permanents opponents control','Lock','Mass land denial'], 'Alta', 'Destruye todos los permanentes de los demás mientras los tuyos son indestructibles.', ['Equipá Worldslayer.','Conectá daño de combate.','Worldslayer destruye permanentes no indestructibles.'], ['La criatura equipada debe conectar.']),
  combo('Basalt Monolith + Rings of Brighthearth', ['Basalt Monolith','Rings of Brighthearth'], 'Infinite mana', ['Infinite colorless mana'], 'Alta', 'Copia la habilidad de enderezar Basalt Monolith y genera maná infinito.', ['Girás Basalt.','Activás enderezar y copiás con Rings.','Generás más de lo que gastás.'], ['Necesitás maná inicial.'])
]
function combo(name, pieces, type, effects, power, desc, steps, prerequisites){ return {name,pieces,type,effects,power,desc,steps,prerequisites} }

function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim()}
function isDigits(s){return String(s||'').split('').every(ch=>ch>='0'&&ch<='9')}
function removeTags(s){let out='',d=0; for(const ch of String(s||'')){ if(ch==='['){d++;continue} if(ch===']'){d=Math.max(0,d-1);continue} if(!d)out+=ch } return out}
function extractTags(line){const out=[]; let cur='',inside=false; for(const ch of String(line||'')){ if(ch==='['){inside=true;cur='';continue} if(ch===']'&&inside){inside=false; cur.split(/[;,/]/).map(x=>x.replace(/\{.*?\}/g,'').trim()).filter(Boolean).forEach(x=>out.push(x)); continue} if(inside)cur+=ch } return out}
function cleanName(name){let s=String(name||'').trim(); if(s.toLowerCase().startsWith('sb:')) s=s.slice(3).trim(); const parts=s.split(' ').filter(Boolean); if(parts.length){const f=parts[0].toLowerCase(); const q=f.endsWith('x')?f.slice(0,-1):f; if(isDigits(q)) s=parts.slice(1).join(' ')} s=removeTags(s).replace(/\s+\*[^*]+\*/g,'').trim(); const meta=extractPrinting(s); return meta.name.replace(/\s+/g,' ').trim()}
function extractPrinting(raw){const s=removeTags(raw).trim(); const m=s.match(/^(.*?)\s*\(([A-Za-z0-9]{2,8})\)\s*#?([A-Za-z0-9★☆\-]+)?/); if(!m) return {name:s,setCode:'',collectorNumber:''}; return {name:m[1].trim(),setCode:m[2].toLowerCase(),collectorNumber:m[3]||''}}
function inferSection(section,fallback='Otros'){const x=norm(section); if(!x)return fallback; if(x.includes('commander'))return 'Commander'; if(x.includes('creature')||x.includes('criatura'))return 'Criaturas'; if(x.includes('artifact')||x.includes('artefact'))return 'Artefactos'; if(x.includes('enchantment')||x.includes('encant'))return 'Encantamientos'; if(x.includes('instant'))return 'Instantáneos'; if(x.includes('sorcery')||x.includes('conjuro')||x.includes('sortilegio'))return 'Sortilegios'; if(x.includes('planeswalker'))return 'Planeswalker'; if(x.includes('land')||x.includes('tierra'))return 'Tierras'; return fallback}
function csvLine(line){const out=[]; let cur='',q=false; for(let i=0;i<line.length;i++){const ch=line[i]; if(ch==='"'&&line[i+1]==='"'){cur+='"';i++;continue} if(ch==='"'){q=!q;continue} if(ch===','&&!q){out.push(cur.trim());cur='';continue} cur+=ch} out.push(cur.trim()); return out}
function col(headers,cands){const hs=headers.map(norm); for(const c of cands){const i=hs.indexOf(norm(c)); if(i>=0)return i} return -1}
function baseCard(row){return {key:norm(row.name),qty:row.qty||1,name:cleanName(row.name),type:inferSection(row.category,'Otros'),tags:row.tags||[],manualTags:row.tags||[],setCode:row.setCode||'',collectorNumber:row.collectorNumber||'',finish:row.finish||'',cmc:null,manaCost:'',colors:[],colorIdentity:[],oracle:'',typeLine:'',image:'',smallImage:'',price:null,legalCommander:true,scryfallLoaded:false,notFound:false}}
function mergeRows(rows){const map=new Map(); for(const r of rows){const c=baseCard(r); if(!c.name)continue; const ex=map.get(c.key); if(ex){ex.qty+=c.qty; ex.tags=[...new Set([...ex.tags,...c.tags])]; ex.manualTags=ex.tags; if(!ex.setCode&&c.setCode)ex.setCode=c.setCode; if(!ex.collectorNumber&&c.collectorNumber)ex.collectorNumber=c.collectorNumber; if(ex.type==='Otros'&&c.type!=='Otros')ex.type=c.type}else map.set(c.key,c)} return [...map.values()]}
function parseDeckCsv(text){const lines=text.replaceAll('\r','').split('\n').map(x=>x.trim()).filter(Boolean); if(lines.length<2)return []; const h=csvLine(lines[0]); const ni=col(h,['name','card name','card','nombre']); if(ni<0)return []; const qi=col(h,['quantity','qty','count','cantidad']); const si=col(h,['set','set code','edition','edicion']); const ci=col(h,['collector number','collector','number','collector_number']); const gi=col(h,['category','categories','section','folder','categoria']); const fi=col(h,['finish','foil']); return mergeRows(lines.slice(1).map(l=>{const r=csvLine(l); return {qty:qi>=0?Number(r[qi]||1)||1:1,name:r[ni]||'',setCode:si>=0?String(r[si]||'').toLowerCase().trim():'',collectorNumber:ci>=0?String(r[ci]||'').trim():'',category:gi>=0?String(r[gi]||'').trim():'',finish:fi>=0?String(r[fi]||'').trim():'',tags:[]}}))}
function parseDeckJson(text){try{const d=JSON.parse(text); const arr=Array.isArray(d)?d:Array.isArray(d.cards)?d.cards:Array.isArray(d.entries)?d.entries:Array.isArray(d.decklist)?d.decklist:[]; return mergeRows(arr.map(x=>{const card=x.card||x; return {qty:Number(x.quantity||x.qty||x.count||1)||1,name:card.name||x.name||x.cardName||x.card_name||'',setCode:String(card.set||card.setCode||x.set||x.setCode||'').toLowerCase().trim(),collectorNumber:String(card.collector_number||card.collectorNumber||x.collector_number||x.collectorNumber||'').trim(),category:String(x.category||x.categories||x.section||'').trim(),finish:String(x.finish||x.foil||'').trim(),tags:[]}}))}catch{return []}}
function parseDecklist(text){const t=String(text||'').trim(); if(!t)return []; if(t.startsWith('{')||t.startsWith('[')){const j=parseDeckJson(t); if(j.length)return j} const first=t.replaceAll('\r','').split('\n').find(Boolean)||''; if(first.includes(',')&&norm(first).includes('name')){const c=parseDeckCsv(t); if(c.length)return c} const headings=new Map([['commander','Commander'],['commanders','Commander'],['creature','Criaturas'],['creatures','Criaturas'],['criaturas','Criaturas'],['artifact','Artefactos'],['artifacts','Artefactos'],['artefactos','Artefactos'],['enchantment','Encantamientos'],['enchantments','Encantamientos'],['encantamientos','Encantamientos'],['instant','Instantáneos'],['instants','Instantáneos'],['instantaneos','Instantáneos'],['sorcery','Sortilegios'],['sorceries','Sortilegios'],['conjuros','Sortilegios'],['planeswalker','Planeswalker'],['planeswalkers','Planeswalker'],['land','Tierras'],['lands','Tierras'],['tierras','Tierras'],['mainboard','Otros'],['sideboard','Otros'],['maybeboard','Otros']]); let section='Otros'; const rows=[]; for(let line of t.replaceAll('\r','').split('\n').map(x=>x.trim()).filter(Boolean)){ if(!line||line.startsWith('//'))continue; if(line.startsWith('#')){section=inferSection(line.slice(1),section); continue} const hk=norm(line.replaceAll(':','')); if(headings.has(hk)){section=headings.get(hk); continue} if(line.toLowerCase().startsWith('sb:')) line=line.slice(3).trim(); const tags=extractTags(line); const meta=extractPrinting(removeTags(line)); let noTags=removeTags(line).trim(); const parts=noTags.split(' ').filter(Boolean); let qty=1, rest=noTags; if(parts.length){const f=parts[0].toLowerCase(); const q=f.endsWith('x')?f.slice(0,-1):f; if(isDigits(q)){qty=Number(q)||1; rest=parts.slice(1).join(' ')}} const m=extractPrinting(rest); const name=cleanName(m.name); if(!name)continue; rows.push({qty,name,setCode:m.setCode||meta.setCode,collectorNumber:m.collectorNumber||meta.collectorNumber,category:section,tags}) } return mergeRows(rows)}

async function fetchCard(card){ if(card?.setCode&&card?.collectorNumber){const r=await fetch(`https://api.scryfall.com/cards/${encodeURIComponent(card.setCode)}/${encodeURIComponent(card.collectorNumber)}`); if(r.ok)return r.json()} const r=await fetch(`https://api.scryfall.com/cards/named?fuzzy=${encodeURIComponent(card?.name||card)}`); if(!r.ok)throw new Error('not found'); return r.json()}
async function autocomplete(q){if(!q||q.trim().length<2)return []; const r=await fetch(`https://api.scryfall.com/cards/autocomplete?q=${encodeURIComponent(q.trim())}`); if(!r.ok)return []; const d=await r.json(); return d.data||[]}
function scry(data){const f=data.card_faces?.[0]; const img=data.image_uris?.normal||f?.image_uris?.normal||''; const small=data.image_uris?.small||f?.image_uris?.small||img; return {name:data.name,setCode:data.set||'',collectorNumber:data.collector_number||'',cmc:data.cmc??0,manaCost:data.mana_cost||f?.mana_cost||'',colors:data.colors||f?.colors||[],colorIdentity:data.color_identity||[],oracle:data.oracle_text||f?.oracle_text||'',typeLine:data.type_line||f?.type_line||'',image:img,smallImage:small,legalCommander:data.legalities?.commander==='legal',price:data.prices?.eur||data.prices?.usd||null,scryfallLoaded:true,notFound:false}}
function typeFrom(card){const t=(card.typeLine||'').toLowerCase(); if(t.includes('land'))return 'Tierras'; if(t.includes('creature'))return 'Criaturas'; if(t.includes('artifact'))return 'Artefactos'; if(t.includes('enchantment'))return 'Encantamientos'; if(t.includes('instant'))return 'Instantáneos'; if(t.includes('sorcery'))return 'Sortilegios'; if(t.includes('planeswalker'))return 'Planeswalker'; return card.type||'Otros'}

function getCommander(cards){return cards.find(c=>c.type==='Commander'||c.tags.some(t=>norm(t).includes('commander')))||cards.find(c=>/legendary creature/i.test(c.typeLine||''))||null}
function hasAny(text,arr){return arr.some(a=>text.includes(a))}
function detectRoles(card){const roles=new Set(card.manualTags||[]); const key=norm(card.name); const oracle=(card.oracle||'').toLowerCase(); const type=(card.typeLine||'').toLowerCase(); const text=`${key} ${oracle} ${type}`; const has=(...xs)=>hasAny(text,xs); const ho=(...xs)=>hasAny(oracle,xs); const names=(...xs)=>xs.map(norm).includes(key); if(card.type==='Tierras'||type.includes('land'))roles.add('Land')
  if(key.includes('signet')||key.includes('talisman')||names('Sol Ring','Arcane Signet','Mind Stone','Fellwar Stone','Thought Vessel','Thran Dynamo','Chromatic Lantern','Wayfarer\'s Bauble')||ho('add {','add one mana','treasure token','create a treasure','search your library')&&ho('land card')||ho('additional land','play an additional land'))roles.add('Ramp')
  if(ho('draw a card','draw two cards','draw three cards','draw x cards','draw cards','investigate','clue token')||ho('put')&&ho('into your hand')&&ho('top'))roles.add('Draw')
  if(ho('destroy target','exile target','target creature gets -','target player sacrifices','fight target','deals damage to target creature','deals damage to any target','return target creature','return target nonland permanent','return target permanent'))roles.add('Removal')
  if(ho('destroy all creatures','destroy all artifacts','destroy all enchantments','destroy all permanents','destroy all nonland permanents','exile all creatures','exile all permanents','each creature gets -','all creatures get -','damage to each creature','deals damage to each creature','return all creatures','return all nonland permanents'))roles.add('Board Wipe')
  if(ho('counter target spell','counter target activated','counter target triggered'))roles.add('Counterspell')
  if(ho('gains hexproof','gain hexproof','gains indestructible','gain indestructible','protection from','phase out','phases out','prevent all damage','regenerate target','ward')||names('Swiftfoot Boots','Lightning Greaves','Heroic Intervention','Teferi\'s Protection','Tamiyo\'s Safekeeping','Tyvar\'s Stand'))roles.add('Protection')
  if(ho('search your library')&&!ho('basic land','land card','forest card','plains card','island card','swamp card','mountain card')||STRONG_TUTORS.has(key))roles.add('Tutor')
  if((ho('create a','create one','create two','create three','create x','creates a')&&ho('token'))||names('Ophiomancer','Tendershoot Dryad','Mycoloth','Awakening Zone','Jadar, Ghoulcaller of Nephalia'))roles.add('Tokens')
  if(ho('sacrifice another creature','sacrifice a creature:','sacrifice a permanent:','sacrifice an artifact:','as an additional cost to cast this spell, sacrifice')||names('Carrion Feeder','Viscera Seer','Bloodflow Connoisseur','Woe Strider','Ashnod\'s Altar','Phyrexian Altar','Altar of Dementia','High Market'))roles.add('Sac Outlet')
  if(ho('each opponent loses','target opponent loses','loses that much life','loses 1 life','lose life')||names('Blood Artist','Zulaport Cutthroat','Bastion of Remembrance','Marauding Blight-Priest','Vito, Thorn of the Dusk Rose','Sanguine Bond'))roles.add('Drain')
  if(ho('you gain','gain life','gains life','lifelink')||names('Soul Warden','Essence Warden','Aetherflux Reservoir'))roles.add('Lifegain')
  if(ho('from your graveyard to your hand','return target card from your graveyard','return target creature card from your graveyard','escape'))roles.add('Recursion')
  if(ho('from your graveyard to the battlefield','put target creature card from a graveyard onto the battlefield')||names('Animate Dead','Reanimate','Victimize','Living Death','Dance of the Dead','Necromancy')){roles.add('Recursion');roles.add('Reanimator')}
  if(ho('untap target','untap another','untap up to','untap it','untap that','untap this'))roles.add('Untap')
  if(ho('can\'t be blocked','unblockable','flying','trample','menace','shadow','horsemanship'))roles.add('Evasion')
  if(type.includes('equipment')||ho('equip ','equipped creature'))roles.add('Equipment')
  if(type.includes('aura')||ho('enchanted creature'))roles.add('Voltron')
  if(ho('exile','return it to the battlefield')||ho('exile another target','then return'))roles.add('Blink')
  if(ho('enters the battlefield','when this enters','whenever a creature enters','whenever another creature enters'))roles.add('ETB')
  if(ho('whenever you cast an instant or sorcery','copy target instant','copy target sorcery','instant and sorcery card','magecraft','storm'))roles.add('Spellslinger')
  if(ho('artifact you control','artifacts you control','whenever an artifact','sacrifice an artifact','affinity for artifacts','improvise'))roles.add('Artifacts')
  if(ho('enchantment you control','whenever you cast an enchantment','constellation','enchantment card','aura you control'))roles.add('Enchantress')
  if(ho('choose a creature type','kindred','creatures you control of the chosen type','other creatures you control get','share a creature type'))roles.add('Tribal')
  if(ho('+1/+1 counter','-1/-1 counter','counter on','counters on','double the number of counters','move a counter'))roles.add('Counters')
  if(ho('proliferate'))roles.add('Proliferate')
  if(ho('can\'t cast','can\'t attack','can\'t untap','players can\'t','opponents can\'t','unless they pay','spells cost'))roles.add('Stax')
  if(ho('goad'))roles.add('Goad')
  if(ho('gain control','you may cast','you may play','from an opponent\'s graveyard'))roles.add('Theft')
  if(ho('take an extra turn','extra turn after this one')||EXTRA_TURNS.has(key))roles.add('Extra Turns')
  if(MLD.has(key))roles.add('Mass Land Denial')
  if(ho('win the game','you win the game')||GAME_CHANGERS.has(key))roles.add('Combo')
  if(GAME_CHANGERS.has(key))roles.add('Game Changer')
  if(FAST_MANA.has(key))roles.add('Fast Mana')
  if(ho('you win the game','each opponent loses','extra combat')||names('Exsanguinate','Torment of Hailfire','Craterhoof Behemoth','Finale of Devastation','Aetherflux Reservoir','Overwhelming Stampede','Triumph of the Hordes'))roles.add('Finisher')
  return [...roles].filter(Boolean)}
function countBy(cards,fn){const m=new Map(); for(const c of cards){const k=fn(c); m.set(k,(m.get(k)||0)+c.qty)} return [...m.entries()].map(([name,value])=>({name,value}))}
function rolesAgg(cards){const m=new Map(); for(const c of cards){for(const r of detectRoles(c)){m.set(r,(m.get(r)||0)+c.qty)}} return [...m.entries()].map(([role,count])=>({role,count,color:ROLE_COLORS[role]||ROLE_COLORS.Other})).sort((a,b)=>b.count-a.count)}
function avgCmc(cards){const a=cards.filter(c=>c.type!=='Tierras'&&c.type!=='Commander'&&typeof c.cmc==='number'); const q=a.reduce((s,c)=>s+c.qty,0); return q?(a.reduce((s,c)=>s+c.cmc*c.qty,0)/q):0}
function combosFor(cards){const names=new Set(cards.map(c=>norm(c.name))); return COMBOS.map(combo=>{const present=combo.pieces.filter(p=>names.has(norm(p))); const missing=combo.pieces.filter(p=>!names.has(norm(p))); return {...combo,present,missing,complete:missing.length===0}})}
function findCard(cards,name){const k=norm(name); return cards.find(c=>c.key===k||norm(c.name)===k)}
function roleCount(cards,r){return rolesAgg(cards).find(x=>x.role===r)?.count||0}
function archetypes(cards){const roles=rolesAgg(cards); const count=r=>roles.find(x=>x.role===r)?.count||0; const types=countBy(cards,c=>c.type); const creatures=types.find(t=>t.name==='Criaturas')?.value||0; const inst=types.find(t=>t.name==='Instantáneos')?.value||0; const sorc=types.find(t=>t.name==='Sortilegios')?.value||0; const artifacts=types.find(t=>t.name==='Artefactos')?.value||0; const ench=types.find(t=>t.name==='Encantamientos')?.value||0; const cmd=getCommander(cards); const cname=norm(cmd?.name||''); const avg=avgCmc(cards); const combos=combosFor(cards).filter(c=>c.complete&&c.pieces.length<=2); const push=[]; const add=(name,score,evidence=[])=>{if(score>=35)push.push({name,score:Math.min(98,Math.round(score)),evidence})}
  const sel=cname.includes('selvala, heart of the wilds'), dina=cname.includes('dina, soul steeper'), giada=cname.includes('giada'), yuriko=cname.includes('yuriko'), mul=cname.includes('muldrotha')
  add('Big Mana / Stompy',count('Ramp')*6+count('Untap')*7+count('Finisher')*5+(avg>=3.6?14:0)+(creatures>=24?8:0)+(sel?36:0),['ramp','untap','finishers',cmd?.name].filter(Boolean))
  add('Creature Combo',combos.length*30+count('Untap')*10+(count('Ramp')>=8?8:0)+(sel?26:0),[combos.length?`${combos.length} combo(s) compactos`:null,'untap',cmd?.name].filter(Boolean))
  add('Aristocrats',count('Sac Outlet')*15+count('Drain')*13+count('Tokens')*4+(count('Recursion')+count('Reanimator'))*4+(dina?24:0),['sac outlets','drain','tokens/cementerio'])
  add('Lifegain / Drain',count('Lifegain')*9+count('Drain')*10+(dina?22:0),['lifegain','drain',cmd?.name].filter(Boolean))
  add('Tokens',count('Tokens')*7+(count('Sac Outlet')>=2?8:0)+(count('Finisher')>=2?5:0)-(sel?22:0),['tokens'])
  add('Counters',count('Counters')*8+count('Proliferate')*11+(creatures>=24?4:0),['contadores'])
  add('Graveyard / Reanimator',(count('Recursion')+count('Reanimator'))*10+count('Reanimator')*8+(mul?35:0),['recursión','reanimación',cmd?.name].filter(Boolean))
  add('Spellslinger',count('Spellslinger')*20+(inst+sorc>=24?22:0),['payoffs de hechizos'])
  add('Artifacts',count('Artifacts')*16+(Math.max(0,artifacts-count('Ramp'))>=12?22:0),['artefactos'])
  add('Enchantress',count('Enchantress')*16+(ench>=18?22:0),['encantamientos'])
  add('Voltron',count('Equipment')*10+count('Voltron')*13+count('Evasion')*3,['equipos/auras'])
  add('Blink / ETB',count('Blink')*15+count('ETB')*6,['blink','ETB'])
  add('Tribal Creature',count('Tribal')*16+(creatures>=32?12:0)+(giada?25:0)+(yuriko?25:0),['tribal',cmd?.name].filter(Boolean))
  push.sort((a,b)=>b.score-a.score); if(!push.length)return [{name:creatures>=28?'Creature Midrange':'Value / Goodstuff',score:55,evidence:['sin arquetipo dominante claro']}]; if(push[1]&&push[1].score>=push[0].score*.82){return [{name:`${push[0].name} + ${push[1].name}`,score:push[0].score,evidence:[...new Set([...push[0].evidence,...push[1].evidence])].slice(0,5)},...push.slice(0,3)]} return push.slice(0,4)}
function scoreMin(v,t,max=90){return v>=t?max:Math.max(25,(v/t)*max)}
function scoreTarget(v,t,tol=1,max=92){const diff=Math.abs(v-t); return diff<=tol?max:Math.max(25,max-diff*12)}
function commanderCentric(cards){const c=getCommander(cards); const text=`${c?.name||''} ${c?.oracle||''}`.toLowerCase(); return !!c&&(text.includes('whenever')||text.includes('{t}')||text.includes('tap:')||norm(c.name).includes('selvala')||norm(c.name).includes('dina')||norm(c.name).includes('giada')||norm(c.name).includes('yuriko'))}
function scores(cards){const lands=cards.filter(c=>c.type==='Tierras').reduce((s,c)=>s+c.qty,0); const avg=avgCmc(cards); const arch=archetypes(cards)[0]?.name||''; const combos=combosFor(cards).filter(c=>c.complete&&c.pieces.length<=2); const rampT=arch.includes('Big Mana')?11:avg>=3.6?10:8; const drawT=arch.includes('Spellslinger')?11:8; const landT=avg>=4?37:avg<=2.6?34:36; const intT=8; const protT=commanderCentric(cards)?4:3; const interaction=roleCount(cards,'Removal')+roleCount(cards,'Counterspell')+roleCount(cards,'Board Wipe'); const fin=roleCount(cards,'Finisher')+roleCount(cards,'Drain')+combos.length*2; const manabase=scoreTarget(lands,landT,1); const ramp=scoreMin(roleCount(cards,'Ramp'),rampT); const draw=scoreMin(roleCount(cards,'Draw'),drawT); const inter=scoreMin(interaction,intT,88); const win=Math.min(94,scoreMin(fin,arch.includes('Big Mana')?5:4,86)+combos.length*4); const synergy=Math.min(95,35+(archetypes(cards)[0]?.score||55)*.55+Math.min(12,synergyLines(cards).length*4)+Math.min(8,combos.length*4)); const curve=arch.includes('Big Mana')?(avg<=4.8?82:65):(avg<=3.3?88:avg<=3.8?75:58); const consistency=Math.min(94,30+Math.min(24,roleCount(cards,'Ramp')*2.4)+Math.min(24,roleCount(cards,'Draw')*2.4)+curve*.18+(combos.length?6:0)); const resil=Math.min(90,scoreMin(roleCount(cards,'Protection')+Math.min(2,roleCount(cards,'Recursion')+roleCount(cards,'Reanimator')),protT,84)); const overall=(manabase*.14+ramp*.13+draw*.15+inter*.12+win*.13+synergy*.18+consistency*.1+resil*.05)/10; return {overall:Math.max(1,Math.min(10,overall)).toFixed(1), radar:[['Manabase',manabase],['Ramp',ramp],['Card Draw',draw],['Interacción',inter],['Win Cons',win],['Sinergia',synergy],['Consistencia',consistency],['Resiliencia',resil]].map(([subject,value])=>({subject,value:Math.round(value)})), targets:{landT,rampT,drawT,intT,protT}}}
function bracket(cards){const game=cards.filter(c=>GAME_CHANGERS.has(c.key)); const fast=cards.filter(c=>FAST_MANA.has(c.key)); const tutors=cards.filter(c=>STRONG_TUTORS.has(c.key)); const mld=cards.filter(c=>MLD.has(c.key)); const turns=cards.filter(c=>EXTRA_TURNS.has(c.key)); const complete=combosFor(cards).filter(c=>c.complete); const compact=complete.filter(c=>c.pieces.length<=2); let b=2; const up=[],down=[],boxes=[]; if(game.length){b=Math.max(b,3); up.push(`${game.length} Game Changer(s): ${game.map(c=>c.name).join(', ')}`); boxes.push({title:'Game Changers',cards:game.map(c=>c.name),note:'Cartas de alto impacto.'})} if(game.length>=4){b=Math.max(b,4); up.push('4+ Game Changers empujan a Bracket 4.')} if(compact.length){b=Math.max(b,4); up.push(`Combo(s) de 2 cartas: ${compact.map(c=>c.name).join(', ')}`); boxes.push({title:'Combos compactos',cards:[...new Set(compact.flatMap(c=>c.pieces))],note:'Si son rápidas/tutoreables empujan a alto poder.'})} if(fast.length>=2){b=Math.max(b,4); up.push(`Fast mana premium: ${fast.map(c=>c.name).join(', ')}`)} if(tutors.length>=2){b=Math.max(b,4); up.push(`Varios tutores eficientes: ${tutors.map(c=>c.name).join(', ')}`)} if(mld.length){b=Math.max(b,4); up.push(`Mass land denial/lock: ${mld.map(c=>c.name).join(', ')}`)} if(turns.length>=2){b=Math.max(b,4); up.push(`Paquete de turnos extra: ${turns.map(c=>c.name).join(', ')}`)} if(!game.length)down.push('Sin Game Changers detectados.'); if(!compact.length)down.push('Sin combos compactos de 2 cartas detectados.'); if(!tutors.length)down.push('Sin tutores premium detectados.'); if(!fast.length)down.push('Sin fast mana premium.'); if(roleCount(cards,'Draw')<7)down.push('Card draw por debajo de una lista optimizada.'); const labels={1:'Exhibición',2:'Básico',3:'Mejorado',4:'Optimizado',5:'cEDH'}; return {bracket:b,label:labels[b],up,down,boxes,game,fast,tutors,mld,turns,compact}}
function synergyLines(cards){const lines=[]; const add=(name,roles,desc)=>{const pieces=[...new Set(roles.flatMap(r=>cards.filter(c=>detectRoles(c).includes(r)).slice(0,4).map(c=>c.name)))].slice(0,8); if(pieces.length)lines.push({name,roles,desc,pieces})}; if(roleCount(cards,'Sac Outlet')&&roleCount(cards,'Drain'))add('Motor Aristocrats',['Sac Outlet','Drain','Tokens','Recursion'],'Sacrificar criaturas se convierte en daño, vida o value.'); if(roleCount(cards,'Tokens')>=3&&(roleCount(cards,'Draw')||roleCount(cards,'Sac Outlet')))add('Tokens como combustible',['Tokens','Draw','Sac Outlet','Drain'],'Los tokens alimentan sacrificios, robo o drenaje.'); if(roleCount(cards,'Lifegain')>=2&&roleCount(cards,'Drain')>=2)add('Lifegain convertido en daño',['Lifegain','Drain'],'Las vidas ganadas se vuelven presión real.'); if(roleCount(cards,'Untap')>=1&&roleCount(cards,'Ramp')>=6)add('Untap + maná',['Untap','Ramp','Finisher'],'Enderezar motores de maná sube el techo del mazo.'); if(roleCount(cards,'Blink')>=2&&roleCount(cards,'ETB')>=4)add('Blink / ETB value',['Blink','ETB','Draw','Removal'],'Repetir entradas al campo genera ventaja.'); return lines}
function strategyHint(cards){const c=getCommander(cards); const key=norm(c?.name); if(key.includes('selvala, heart of the wilds'))return {plan:'acelerar con criaturas de mucha fuerza, usar a Selvala como motor de maná/cartas y cerrar con criaturas enormes o combos de enderezar/maná infinito',early:'mano con 2-3 tierras, acelerador temprano y criatura de fuerza alta o pieza de Selvala',mid:'resolver a Selvala protegida, generar maná explosivo y convertirlo en amenazas/tutores/combo',late:'cerrar con combate masivo, Finale/Craterhoof-style effects o Selvala + Umbral Mantle'}; if(key.includes('dina, soul steeper'))return {plan:'convertir ganancia de vida y sacrificios en drenaje constante usando tokens o criaturas pequeñas como combustible',early:'bajar Dina o motores de lifegain baratos y preparar cuerpos sacrificables',mid:'juntar payoffs de drain con sac outlets o tokens',late:'cerrar con drenaje acumulado, Exsanguinate/Aetherflux o loops de lifegain/drain'}; return null}
function planText(cards){if(!cards.length)return 'Pegá una decklist para generar el análisis.'; const arch=archetypes(cards); const hint=strategyHint(cards); const ev=[]; ['Ramp','Draw','Removal','Counters','Tokens','Untap'].forEach(r=>{const n=roleCount(cards,r); if(n)ev.push(`${n} ${r}`)}); const compact=combosFor(cards).filter(c=>c.complete&&c.pieces.length<=2); let out=hint?`El plan principal es ${hint.plan}.`:`El plan principal parece ser ${arch[0]?.name||'Value / Goodstuff'}.`; if(arch[1])out+=` Como subplan aparece ${arch[1].name}.`; if(ev.length)out+=` Señales detectadas: ${ev.join(', ')}.`; if(compact.length)out+=` Puede cerrar por combo: ${compact.map(c=>c.name).join('; ')}.`; return out}
function phases(cards){const h=strategyHint(cards); if(h)return h; return {early:'priorizar tierras, ramp barato y primeras piezas de motor',mid:'bajar payoffs, sostener interacción y no gastar piezas clave antes de generar valor',late:'cerrar con wincons, acumulación de value o combo'}}
function strengths(cards){const a=[]; const arch=archetypes(cards)[0]; if(arch)a.push(['Identidad estratégica',`El mazo apunta a ${arch.name}. Evidencia: ${(arch.evidence||[]).join(', ')}.`]); if(roleCount(cards,'Ramp')>=scores(cards).targets.rampT)a.push(['Ramp suficiente',`Hay ${roleCount(cards,'Ramp')} piezas de ramp.`]); if(roleCount(cards,'Draw')>=scores(cards).targets.drawT)a.push(['Card advantage sano',`Hay ${roleCount(cards,'Draw')} fuentes de draw/value.`]); const inter=roleCount(cards,'Removal')+roleCount(cards,'Counterspell')+roleCount(cards,'Board Wipe'); if(inter>=8)a.push(['Buena interacción',`Hay ${inter} respuestas detectadas.`]); if(!a.length)a.push(['Base inicial','La app detectó estructura, pero conviene cargar Scryfall y revisar tags.']); return a}
function weaknesses(cards){const a=[]; const sc=scores(cards); if(roleCount(cards,'Draw')<sc.targets.drawT)a.push(['Poco robo',`Hay ${roleCount(cards,'Draw')} fuentes; objetivo aprox. ${sc.targets.drawT}.`]); if(roleCount(cards,'Ramp')<sc.targets.rampT)a.push(['Ramp bajo',`Hay ${roleCount(cards,'Ramp')} ramp; objetivo aprox. ${sc.targets.rampT}.`]); const inter=roleCount(cards,'Removal')+roleCount(cards,'Counterspell')+roleCount(cards,'Board Wipe'); if(inter<sc.targets.intT)a.push(['Interacción baja',`Hay ${inter} respuestas; objetivo aprox. ${sc.targets.intT}.`]); if(commanderCentric(cards)&&roleCount(cards,'Protection')<sc.targets.protT)a.push(['Poca protección',`El comandante parece central y hay ${roleCount(cards,'Protection')} protección.`]); if(!a.length)a.push(['Sin agujeros críticos','No se detectan problemas estructurales grandes.']); return a}
function isComboPiece(card,cards){return combosFor(cards).some(co=>co.complete&&co.pieces.some(p=>norm(p)===card.key))}
function coreRoles(cards){const arch=archetypes(cards)[0]?.name||''; const s=new Set(['Draw','Ramp','Removal','Protection']); if(arch.includes('Big Mana'))['Ramp','Untap','Finisher','Counters','Evasion'].forEach(r=>s.add(r)); if(arch.includes('Creature Combo'))['Ramp','Untap','Tutor','Protection','Draw'].forEach(r=>s.add(r)); if(arch.includes('Aristocrats'))['Sac Outlet','Drain','Tokens','Recursion','Draw'].forEach(r=>s.add(r)); if(arch.includes('Lifegain'))['Lifegain','Drain','Draw'].forEach(r=>s.add(r)); if(arch.includes('Tokens'))['Tokens','Draw','Finisher','Sac Outlet'].forEach(r=>s.add(r)); return s}
function cutCandidates(cards,limit=8){const sc=scores(cards); const core=coreRoles(cards); const arch=archetypes(cards)[0]?.name||''; const protectedKeys=new Set(['sol ring','arcane signet','command tower']); return cards.filter(c=>c.type!=='Commander'&&c.type!=='Tierras'&&!protectedKeys.has(c.key)).map(card=>{const roles=detectRoles(card); const reasons=[]; let score=10; if(isComboPiece(card,cards)){score-=80; reasons.push('pieza de combo detectado')} if(roles.some(r=>core.has(r))){score-=18; reasons.push('rol central del arquetipo')} if(!roles.length){score+=32; reasons.push('sin rol claro detectado')} if(roles.length===1&&['Evasion','ETB','Lifegain'].includes(roles[0])){score+=10; reasons.push('rol aislado de bajo impacto relativo')} if((card.cmc||0)>=6&&!arch.includes('Big Mana')){score+=14; reasons.push('coste alto para el plan')} if(roles.includes('Ramp')&&roleCount(cards,'Ramp')<=Math.ceil(sc.targets.rampT)){score-=28; reasons.push('no cortar ramp: está cerca/debajo del objetivo')} if(roles.includes('Draw')&&roleCount(cards,'Draw')<=Math.ceil(sc.targets.drawT)){score-=28; reasons.push('no cortar draw: está cerca/debajo del objetivo')} return {card,score,roles,reasons}}).sort((a,b)=>b.score-a.score).slice(0,limit)}
function wantedRole(name){const k=norm(name); if(['skullclamp','phyrexian arena','rhystic study','guardian project','beast whisperer','garruk\'s uprising'].includes(k))return 'Draw'; if(['sol ring','arcane signet','fellwar stone','nature\'s lore','three visits','wild growth','utopia sprawl'].includes(k)||k.includes('signet')||k.includes('talisman'))return 'Ramp'; if(['beast within','generous gift','feed the swarm','swords to plowshares','path to exile'].includes(k))return 'Removal'; if(['heroic intervention','swiftfoot boots','lightning greaves','tamiyo\'s safekeeping','tyvar\'s stand'].includes(k))return 'Protection'; if(['umbral mantle','quirion ranger','scryb ranger','patriar\'s seal','instill energy'].includes(k))return 'Untap'; if(['craterhoof behemoth','finale of devastation','overwhelming stampede','triumph of the hordes','exsanguinate','torment of hailfire'].includes(k))return 'Finisher'; return 'Upgrade'}
function cutsForWanted(cards,wanted){const role=wantedRole(wanted); return cutCandidates(cards,30).map(item=>{let score=item.score; const reasons=[...(item.reasons||[])]; if(item.roles.includes(role)&&['Ramp','Draw','Removal','Protection'].includes(role)){score-=25; reasons.unshift(`no cortar ${role}: estás metiendo ese rol`)} if(['Finisher','Untap','Upgrade'].includes(role)&&!item.roles.length){score+=8; reasons.unshift('la carta nueva sube techo; este slot tiene poco rol')} return {...item,score,reasons}}).sort((a,b)=>b.score-a.score).slice(0,5)}
function report(cards){const c=getCommander(cards), sc=scores(cards), br=bracket(cards); return `Commander Deck Analyzer\n\nCommander: ${c?.name||'No detectado'}\nArquetipo: ${archetypes(cards)[0]?.name||'-'}\nOverall: ${sc.overall}/10\nBracket: ${br.bracket} - ${br.label}\nCartas: ${cards.reduce((s,c)=>s+c.qty,0)}\nTierras: ${cards.filter(c=>c.type==='Tierras').reduce((s,c)=>s+c.qty,0)}\nCMC promedio: ${avgCmc(cards).toFixed(2)}\n\nPlan:\n${planText(cards)}\n\nFortalezas:\n${strengths(cards).map(([t,d])=>`- ${t}: ${d}`).join('\n')}\n\nDebilidades:\n${weaknesses(cards).map(([t,d])=>`- ${t}: ${d}`).join('\n')}\n\nFactores bracket:\n${br.up.concat(br.down).map(x=>`- ${x}`).join('\n')}`}

function Tag({label,color}){const pure=String(label).split(' · ')[0]; return <span className="tag" title={ROLE_DESCRIPTIONS[pure]||pure} style={{color:color||ROLE_COLORS[pure]||'#86efac'}}>{label}</span>}
function BarList({data,labelKey='name',valueKey='value',max,onClick}){const m=max||Math.max(1,...data.map(d=>d[valueKey])); return <div className="bar-list">{data.map(d=><div className="bar-row" key={d[labelKey]} onClick={()=>onClick?.(d)} style={{cursor:onClick?'pointer':'default'}}><div className="bar-label" title={ROLE_DESCRIPTIONS[d[labelKey]]||d[labelKey]}>{d[labelKey]}</div><div className="bar-bg"><div className="bar-fill" style={{width:`${Math.max(4,d[valueKey]/m*100)}%`,background:d.color||undefined}} /></div><div className="bar-num">{d[valueKey]}</div></div>)}</div>}
function Stat({icon,value,label,sub}){return <div className="stat"><div className="icon">{icon}</div><div className="v">{value}</div><div className="l">{label}</div>{sub&&<div className="small">{sub}</div>}</div>}

export default function App(){
  const [tab,setTab]=useState('input'),[deckText,setDeckText]=useState(''),[cards,setCards]=useState([]),[loading,setLoading]=useState(false),[status,setStatus]=useState(''),[progress,setProgress]=useState(0)
  const [deckName,setDeckName]=useState(''),[saved,setSaved]=useState([]),[saveStatus,setSaveStatus]=useState('')
  const [filter,setFilter]=useState(null),[search,setSearch]=useState(''),[typeFilter,setTypeFilter]=useState('Todos'),[roleFilter,setRoleFilter]=useState('Todos')
  const [comboView,setComboView]=useState('included'),[wantedSearch,setWantedSearch]=useState(''),[suggestions,setSuggestions]=useState([]),[selected,setSelected]=useState([]),[manualWanted,setManualWanted]=useState(''),[reportOpen,setReportOpen]=useState(false)
  useEffect(()=>{try{setSaved(JSON.parse(localStorage.getItem(SAVED_KEY)||'[]'))}catch{setSaved([])}},[])
  const commander=useMemo(()=>getCommander(cards),[cards]), total=cards.reduce((s,c)=>s+c.qty,0), lands=cards.filter(c=>c.type==='Tierras').reduce((s,c)=>s+c.qty,0), avg=avgCmc(cards), sc=scores(cards), br=bracket(cards), arch=archetypes(cards), roles=rolesAgg(cards), types=countBy(cards,c=>c.type), curve=countBy(cards.filter(c=>c.type!=='Tierras'&&c.type!=='Commander'),c=>typeof c.cmc==='number'?(c.cmc>=7?'7+':String(c.cmc)):'?').sort((a,b)=>String(a.name).localeCompare(String(b.name)))
  const allTypes=['Todos',...new Set(cards.map(c=>c.type))], allRoles=['Todos',...new Set(cards.flatMap(c=>detectRoles(c)))].sort((a,b)=>a==='Todos'?-1:b==='Todos'?1:a.localeCompare(b))
  const filtered=cards.filter(c=>!filter||(filter.kind==='cmc'?((typeof c.cmc==='number'?(c.cmc>=7?'7+':String(c.cmc)):'?')===filter.value):filter.kind==='type'?c.type===filter.value:detectRoles(c).includes(filter.value))).filter(c=>typeFilter==='Todos'||c.type===typeFilter).filter(c=>roleFilter==='Todos'||detectRoles(c).includes(roleFilter)).filter(c=>!search||norm(c.name).includes(norm(search)))
  const comboData=combosFor(cards), included=comboData.filter(c=>c.complete&&c.pieces.length>=2&&c.pieces.length<=3), almost=comboData.filter(c=>!c.complete&&c.pieces.length>=2&&c.pieces.length<=3&&c.present.length>=c.pieces.length-1), shownCombos=comboView==='included'?included:almost
  const phasesData=phases(cards)

  async function enrich(list){setLoading(true); setProgress(0); const next=[...list]; setCards(next); for(let i=0;i<next.length;i++){setStatus(`Cargando Scryfall ${i+1}/${next.length}: ${next[i].name}`); try{const data=await fetchCard(next[i]); const merged={...next[i],...scry(data)}; merged.type=typeFrom(merged); merged.roles=detectRoles(merged); next[i]=merged}catch{next[i]={...next[i],notFound:true}} setCards([...next]); setProgress(Math.round((i+1)/next.length*100)); await sleep(90)} setLoading(false); setStatus('Datos Scryfall cargados.'); return next}
  async function analyze(){const parsed=parseDecklist(deckText).map(c=>({...c,roles:detectRoles(c)})); setCards(parsed); setFilter(null); setSearch(''); setTypeFilter('Todos'); setRoleFilter('Todos'); const cmd=getCommander(parsed); if(!deckName&&cmd?.name)setDeckName(cmd.name); setTab('overview'); await enrich(parsed)}
  function upload(e){const f=e.target.files?.[0]; if(!f)return; const reader=new FileReader(); reader.onload=()=>{setDeckText(String(reader.result||'')); setStatus(`Archivo cargado: ${f.name}`)}; reader.readAsText(f); e.target.value=''}
  function saveDeck(){if(!cards.length){setSaveStatus('Primero analizá una decklist.'); return} const now=new Date().toISOString(); const name=deckName.trim()||commander?.name||'Mazo sin nombre'; const record={id:String(Date.now()),name,commanderName:commander?.name||'No detectado',deckText,cards:cards.map(c=>({...c,roles:undefined})),updatedAt:now,summary:{total,lands,avg:avg.toFixed(2),overall:sc.overall,bracket:br.bracket,bracketLabel:br.label,archetypes:arch.map(a=>a.name),commanderImage:commander?.smallImage||commander?.image||'',combos:included.length}}; const old=JSON.parse(localStorage.getItem(SAVED_KEY)||'[]'); const idx=old.findIndex(d=>norm(d.name)===norm(name)); const next=idx>=0?[...old]:[record,...old]; if(idx>=0)next[idx]={...record,id:old[idx].id}; localStorage.setItem(SAVED_KEY,JSON.stringify(next)); setSaved(next); setSaveStatus(idx>=0?`Actualizado: ${name}`:`Guardado: ${name}`)}
  function openDeck(d){setDeckName(d.name); setDeckText(d.deckText); setCards((d.cards||[]).map(c=>({...c,roles:detectRoles(c)}))); setTab('overview'); setSaveStatus(`Cargado: ${d.name}`)}
  function delDeck(id){const next=saved.filter(d=>d.id!==id); localStorage.setItem(SAVED_KEY,JSON.stringify(next)); setSaved(next)}
  async function searchWanted(){const s=await autocomplete(wantedSearch); setSuggestions(s.slice(0,8))}
  const wantedList=[...new Set([...selected,...manualWanted.split('\n').map(x=>x.trim()).filter(Boolean)])]
  const tabs=[['decks','📚 Decks'],['input','🧾 Input'],['overview','📊 Overview'],['bracket','🏷️ Bracket'],['combos','🧩 Combos'],['analysis','🔬 Análisis'],['improve','🔧 Mejoras'],['swap','🔁 Meter cartas'],['hands','🖐️ Manos'],['cards','🖼️ Cartas']]

  return <div className="app">
    <header className="hero">
      <div className="hero-left">{commander?.smallImage&&<img className="commander-img" src={commander.smallImage} alt={commander.name}/>}<div><div className="eyebrow">Commander · Universal Deck Analyzer · EDH</div><h1 className="title">{commander?commander.name:'Commander Deck Analyzer'}</h1><div className="chips">{(arch.length?arch:[{name:'Pega una decklist',score:0}]).map(a=><Tag key={a.name} label={`${a.name}${a.score?` · ${a.score}`:''}`} />)}</div></div></div>
      <div className="hero-stats">{cards.length>0&&<div className="save-box"><div className="small">Guardar análisis</div><input className="input" value={deckName} onChange={e=>setDeckName(e.target.value)} placeholder="Nombre del deck"/><button className="btn primary" onClick={saveDeck} style={{width:'100%',marginTop:8}}>Guardar deck</button>{saveStatus&&<div className="status">{saveStatus}</div>}</div>}<div className="score-card amber"><div className="num">{cards.length?sc.overall:'-'}</div><div className="label">Overall /10</div></div><div className="score-card"><div className="num">{cards.length?br.bracket:'-'}</div><div className="label">Bracket</div></div></div>
    </header>
    {cards.length>0&&<div className="grid stats"><Stat icon="🃏" value={total} label="Cartas" sub={total===100?'Commander legal':`${Math.abs(total-100)} ${total>100?'sobran':'faltan'}`}/><Stat icon="⚡" value={avg?avg.toFixed(2):'-'} label="CMC prom."/><Stat icon="🌍" value={lands} label="Tierras"/><Stat icon="🎭" value={arch[0]?.name?.split(' ')[0]||'-'} label="Arquetipo"/><Stat icon="🏷️" value={br.bracket} label="Bracket" sub={br.label}/><Stat icon="⭐" value={sc.overall} label="Overall"/></div>}
    <nav className="tabs">{tabs.map(([id,l])=><button key={id} className={`tab ${tab===id?'active':''}`} onClick={()=>setTab(id)}>{l}</button>)}</nav>
    {tab==='input'&&<div className="grid two"><section className="panel"><h2>Importar decklist</h2><p className="muted">Acepta texto de Archidekt/Moxfield/Manabox/Arena, CSV/JSON exportado, tags manuales y edición exacta tipo <b>1 Sol Ring (CMM) 703 [Ramp]</b>.</p><div className="mini-card"><b>Formatos válidos</b><br/>1 Sol Ring<br/>1x Sol Ring (CMM) 703 [Ramp]<br/># Commander / # Lands<br/>CSV: Name, Quantity, Set Code, Collector Number</div><label className="btn" style={{display:'block',marginTop:12,textAlign:'center'}}>Subir archivo .txt/.csv/.json<input type="file" accept=".txt,.csv,.json,.dek" onChange={upload} style={{display:'none'}}/></label><button className="btn primary" disabled={loading||!deckText.trim()} onClick={analyze} style={{width:'100%',marginTop:12}}>{loading?'Analizando y cargando Scryfall...':'Analizar decklist + cargar Scryfall'}</button>{loading&&<div className="progress"><div style={{width:`${progress}%`}}/></div>}<div className="status">{status}</div></section><section className="panel"><textarea className="textarea" value={deckText} onChange={e=>setDeckText(e.target.value)} placeholder="Pegá tu decklist acá..."/></section></div>}
    {tab==='overview'&&<div className="grid two"><section className="panel"><h3 className="panel-title">Curva de maná</h3><BarList data={curve} labelKey="name" max={Math.max(1,...curve.map(x=>x.value))} onClick={d=>{setFilter({kind:'cmc',value:d.name});setTab('cards')}}/></section><section className="panel"><h3 className="panel-title">Tipos de carta</h3><BarList data={types} onClick={d=>{setFilter({kind:'type',value:d.name});setTab('cards')}}/></section><section className="panel"><h3 className="panel-title">Roles detectados</h3><BarList data={roles.slice(0,14)} labelKey="role" valueKey="count" onClick={d=>{setFilter({kind:'role',value:d.role});setTab('cards')}}/></section><section className="panel"><h3 className="panel-title">Plan de juego detectado</h3><p className="muted">{planText(cards)}</p><button className="btn" onClick={()=>setReportOpen(!reportOpen)}>{reportOpen?'Ocultar reporte':'Exportar reporte'}</button>{reportOpen&&<div className="report-box" style={{marginTop:12}}>{report(cards)}</div>}</section></div>}
    {tab==='bracket'&&<div className="grid two"><section className="panel"><h2>Bracket {br.bracket} — {br.label}</h2><p className="muted">El bracket no es una nota pura de poder: comunica qué contiene el mazo. El Overall mide salud estructural.</p><div className="mini-grid"><Stat icon="✨" value={br.game.length} label="Game Changers"/><Stat icon="🧩" value={br.compact.length} label="Combos 2 cartas"/><Stat icon="🔎" value={br.tutors.length} label="Tutores"/><Stat icon="⚡" value={br.fast.length} label="Fast mana"/></div></section><section className="panel"><h3>Cartas relevantes</h3>{br.boxes.length?br.boxes.map(b=><div className="mini-card" key={b.title}><b>{b.title}</b><div className="chips" style={{marginTop:8}}>{b.cards.map(c=><Tag key={c} label={c}/>)}</div><p className="small">{b.note}</p></div>):<p className="muted">No hay Game Changers ni combos compactos detectados.</p>}</section><section className="panel"><h3>Qué lo sube</h3>{(br.up.length?br.up:['No hay factores fuertes.']).map(x=><div className="mini-card" key={x}>+ {x}</div>)}</section><section className="panel"><h3>Qué lo frena</h3>{br.down.map(x=><div className="mini-card red" key={x}>- {x}</div>)}</section></div>}
    {tab==='combos'&&<div className="panel"><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap',alignItems:'center'}}><h2>Combos</h2><div className="combo-toggle"><button className={comboView==='included'?'active':''} onClick={()=>setComboView('included')}>Incluidos ({included.length})</button><button className={`amber ${comboView==='almost'?'active':''}`} onClick={()=>setComboView('almost')}>Casi incluidos ({almost.length})</button></div></div>{shownCombos.length===0&&<p className="muted">{comboView==='included'?'No hay combos completos de 2 o 3 cartas detectados.':'No hay combos casi completos; aparecen cuando falta solo una pieza.'}</p>}{shownCombos.map(co=><ComboCard key={co.name} combo={co} cards={cards}/>) }<h3>Motores de sinergia</h3><div className="mini-grid">{synergyLines(cards).map(l=><div className="mini-card" key={l.name}><b>{l.name}</b><p className="small">{l.desc}</p><div className="chips">{l.roles.map(r=><Tag key={r} label={r}/>)}</div><p className="small">Piezas: {l.pieces.join(', ')}</p></div>)}</div></div>}
    {tab==='analysis'&&<div className="grid two"><section className="panel"><h3>Fortalezas</h3>{strengths(cards).map(([t,d])=><div className="mini-card" key={t}><b>{t}</b><p className="small">{d}</p></div>)}</section><section className="panel"><h3>Debilidades</h3>{weaknesses(cards).map(([t,d])=><div className="mini-card red" key={t}><b>{t}</b><p className="small">{d}</p></div>)}</section><section className="panel"><h3>Diagnóstico por rol</h3><BarList data={sc.radar} labelKey="subject"/></section><section className="panel"><h3>Plan de partida</h3><div className="mini-card"><b>Early</b><p className="small">{phasesData.early}</p></div><div className="mini-card"><b>Mid</b><p className="small">{phasesData.mid}</p></div><div className="mini-card"><b>Late</b><p className="small">{phasesData.late}</p></div></section></div>}
    {tab==='improve'&&<div className="grid two"><section className="panel"><h3>Primeros slots revisables</h3>{cutCandidates(cards,10).map(({card,score,roles,reasons},i)=><div className="mini-card" key={card.key}><b>{i+1}. {card.name}</b><p className="small">Score corte: {score}. Roles: {roles.join(', ')||'sin rol'}. {reasons.slice(0,2).join(' · ')}</p></div>)}</section><section className="panel"><h3>Recomendaciones estructurales</h3>{weaknesses(cards).map(([t,d])=><div className="mini-card warn" key={t}><b>{t}</b><p className="small">{d}</p></div>)}</section></div>}
    {tab==='swap'&&<div className="grid two"><section className="panel"><h3>Cartas que querés meter</h3><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><input className="input" value={wantedSearch} onChange={e=>setWantedSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')searchWanted()}} placeholder="Ej: Skullclamp"/><button className="btn" onClick={searchWanted}>Buscar</button><button className="btn" onClick={()=>{if(wantedSearch.trim())setSelected([...new Set([...selected,wantedSearch.trim()])])}}>Añadir texto</button></div><div className="chips" style={{marginTop:10}}>{suggestions.map(s=><button className="btn" key={s} onClick={()=>{setSelected([...new Set([...selected,s])]);setWantedSearch('');setSuggestions([])}}>+ {s}</button>)}</div><div className="chips">{selected.map(s=><button className="btn amber" key={s} onClick={()=>setSelected(selected.filter(x=>x!==s))}>{s} ✕</button>)}</div><textarea className="textarea" style={{minHeight:140,marginTop:10}} value={manualWanted} onChange={e=>setManualWanted(e.target.value)} placeholder={'O pegá varias:\nSkullclamp\nTendershoot Dryad'}/></section><section className="panel"><h3>Cortes sugeridos</h3>{!wantedList.length&&<p className="muted">Seleccioná o escribí cartas a meter.</p>}{wantedList.map(w=><div className="mini-card" key={w}><b>Para meter: {w}</b><Tag label={wantedRole(w)}/>{cutsForWanted(cards,w).map(({card,score,roles,reasons},i)=><p className="small" key={card.key}>{i+1}. <b>{card.name}</b> — {roles.join(', ')||'sin rol'} · {reasons.slice(0,2).join(' · ')||`score ${score}`}</p>)}</div>)}</section></div>}
    {tab==='hands'&&<Hands cards={cards}/>} 
    {tab==='cards'&&<section className="panel"><div className="gallery-tools"><input className="input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar carta..."/><select className="select" value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}>{allTypes.map(t=><option key={t}>{t}</option>)}</select><select className="select" value={roleFilter} onChange={e=>setRoleFilter(e.target.value)}>{allRoles.map(r=><option key={r}>{r}</option>)}</select><button className="btn" onClick={()=>{setFilter(null);setSearch('');setTypeFilter('Todos');setRoleFilter('Todos')}}>Limpiar</button></div><h3>{filter?`Filtro activo: ${filter.kind} ${filter.value}`:'Todas las cartas'} · {filtered.reduce((s,c)=>s+c.qty,0)}</h3><div className="gallery">{filtered.map(c=><CardTile key={c.key} card={c}/>)}</div></section>}
    {tab==='decks'&&<section className="panel"><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><h2>Decks guardados</h2><p className="muted">Se guardan en este navegador con localStorage.</p></div><button className="btn primary" onClick={()=>setTab('input')}>+ Analizar nuevo</button></div>{!saved.length&&<p className="muted">Todavía no hay decks guardados.</p>}<div className="mini-grid">{saved.map(d=><div className="deck-card" key={d.id}><div className="deck-head"><div className="deck-id">{d.summary?.commanderImage&&<img src={d.summary.commanderImage} alt={d.commanderName}/>}<div><h3 style={{margin:0}}>{d.name}</h3><div className="small">{d.commanderName}</div></div></div><div><Tag label={`${d.summary?.overall||'-'}/10`}/><Tag label={`B${d.summary?.bracket||'-'}`}/></div></div><div className="chips">{(d.summary?.archetypes||[]).slice(0,3).map(a=><Tag key={a} label={a}/>)}</div><p className="small">Cartas {d.summary?.total} · Tierras {d.summary?.lands} · Combos {d.summary?.combos}</p><button className="btn primary" onClick={()=>openDeck(d)}>Abrir</button> <button className="btn red" onClick={()=>delDeck(d.id)}>Borrar</button></div>)}</div></section>}
  </div>
}
function ComboCard({combo,cards}){return <div className={`combo-card ${combo.complete?'':'almost'}`}><div><Tag label={combo.complete?'✓ COMBO INCLUIDO':`CASI INCLUIDO · FALTA ${combo.missing.length}`} color={combo.complete?'#86efac':'#fbbf24'}/><Tag label={combo.power}/></div><h3>{combo.name}</h3><p className="muted">{combo.desc}</p>{!combo.complete&&<p style={{color:'#fbbf24'}}>Te falta: <b>{combo.missing.join(', ')}</b></p>}<div className="chips">{combo.effects.map(e=><Tag key={e} label={e}/>)}</div><div className="combo-pieces">{combo.pieces.map(p=>{const card=findCard(cards,p), present=combo.present.includes(p); return <div className={`piece ${present?'':'missing'}`} key={p}><div className="piece-img">{card?.image?<img src={card.image}/>:<span>{p}<br/>{present?'En mazo':'Falta'}</span>}</div><b>{p}</b><div className="small">{present?'Detectada':'Carta faltante'}</div></div>})}</div><div className="three-cols"><div className="mini-card"><b>Cómo funciona</b><ol>{combo.steps.map(s=><li key={s}>{s}</li>)}</ol></div><div className="mini-card"><b>Efectos</b><ul>{combo.effects.map(e=><li key={e}>{e}</li>)}</ul></div><div className="mini-card"><b>Requisitos</b><ul>{combo.prerequisites.map(p=><li key={p}>{p}</li>)}</ul></div></div></div>}
function CardTile({card}){const [mvp,setMvp]=useState(localStorage.getItem(`mvp:${card.key}`)==='1'),[dead,setDead]=useState(localStorage.getItem(`dead:${card.key}`)==='1'); function set(k,v,fn){localStorage.setItem(`${k}:${card.key}`,v?'1':'0'); fn(v)} return <div className="card-tile"><div className="card-image">{card.image?<img src={card.image} alt={card.name}/>:<span>Sin imagen<br/>Cargá Scryfall</span>}</div><div className="card-name">{card.qty}x {card.name}</div><div className="card-meta">{card.typeLine||card.type}{card.setCode&&` · ${card.setCode.toUpperCase()} ${card.collectorNumber}`}</div><div className="chips">{detectRoles(card).slice(0,5).map(r=><Tag key={r} label={r}/>)}</div><div style={{display:'flex',gap:7,marginTop:9}}><button className={`btn ${mvp?'primary':''}`} onClick={()=>set('mvp',!mvp,setMvp)}>⭐ MVP</button><button className={`btn ${dead?'red':''}`} onClick={()=>set('dead',!dead,setDead)}>💀 Muerta</button></div></div>}
function Hands({cards}){const [hands,setHands]=useState([]); function draw(){const deck=cards.flatMap(c=>Array(c.qty).fill(c)); const out=[]; for(let h=0;h<10;h++){const pool=[...deck].sort(()=>Math.random()-.5).slice(0,7); const lands=pool.filter(c=>c.type==='Tierras').length; const early=pool.filter(c=>c.type!=='Tierras'&&typeof c.cmc==='number'&&c.cmc<=2).length; const verdict=lands>=2&&lands<=4&&early>=1?'Keep':lands>=2&&lands<=5?'Keep dudoso':'Mulligan'; out.push({pool,lands,early,verdict})} setHands(out)} return <section className="panel"><h2>Simulador de manos</h2><button className="btn primary" onClick={draw}>Simular 10 manos</button><div className="grid" style={{marginTop:12}}>{hands.map((h,i)=><div className="hand" key={i}><b>Mano {i+1}: {h.verdict}</b><p className="small">Tierras {h.lands} · Jugadas ≤2: {h.early}</p><div className="hand-cards">{h.pool.map((c,j)=><span className="pill" key={j}>{c.name}</span>)}</div></div>)}</div></section>}
